[package]
name = "argument-binding"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
ast-types = { path = "../infrastructure/ast-types" }
shared-types = { path = "../infrastructure/shared-types" }
thiserror = { workspace = true }
