[package]
name = "neuro-std"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
shared-types = { path = "../../compiler/infrastructure/shared-types" }
serde.workspace = true