# NEURO Interpreter: Executes the Abstract Syntax Tree (AST) generated by the parser.

# Import AST node types and custom errors
import sys
import os
import src.neuro_ast as neuro_ast # Use alias to avoid standard library conflicts
from src.errors import NeuroInterpreterError, NeuroNameError, NeuroTypeError
# Import the actual network model
from src.models import NeuralNetwork
import torch

class NeuroInterpreter:
    def __init__(self):
        self.variables = {} # Stores defined models, potentially data later
        self.config = {      # Stores global config like loss, optimizer
            'loss': None,
            'optimizer': None
        }

    def interpret(self, node):
        """Interprets the AST starting from the given node (usually Program)."""
        # The main entry point now expects an AST node object
        if not isinstance(node, neuro_ast.ASTNode):
            raise NeuroInterpreterError(f"Interpreter received non-AST input: {type(node)}")
        
        print("Interpreting AST...")
        result = self.visit(node) # Start visiting from the root node
        print("Interpretation complete.")
        return result # Might return final evaluation result, etc.

    def visit(self, node):
        """Visits a node in the AST and calls the appropriate handler."""
        # Use the class name of the node to find the visitor method
        method_name = f'visit_{node.__class__.__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        # print(f"Visiting {node.__class__.__name__} using {visitor.__name__}") # Debugging
        return visitor(node)

    def generic_visit(self, node):
        """Handles unknown AST node types."""
        raise NeuroInterpreterError(f"No visitor method found for AST node type '{node.__class__.__name__}'")

    # --- Visitor Methods for AST Nodes ---

    def visit_Program(self, node: neuro_ast.Program):
        """Executes all statements in the program body."""
        last_result = None
        for statement in node.body:
            last_result = self.visit(statement)
        return last_result # Return result of the last statement

    def visit_AssignmentStatement(self, node: neuro_ast.AssignmentStatement):
        """Handles assignment statements like 'model = NeuralNetwork(...)'"""
        target_name = node.target.name
        print(f"Assigning to variable: {target_name}")
        value = self.visit(node.value) # Evaluate the right-hand side
        
        # If the value is a ModelDefinition result, create the actual network
        if isinstance(value, dict) and value.get('type') == 'ModelDefinition':
            model_params = value['params']
            model_layers = value['layers']
            # Create the actual PyTorch model instance
            # The ModelDefinition node itself holds the name from the assignment
            model_object = NeuralNetwork(name=value['name'], params=model_params, layer_nodes=model_layers)
            self.variables[target_name] = model_object
            print(f"  Stored NeuralNetwork object '{target_name}' in variables.")
        # Handle other assignment types if needed (e.g., loss = Loss(...))
        elif isinstance(value, dict) and value.get('type') == 'LossDefinition':
             print(f"Configuring loss: {value['params']}")
             self.config['loss'] = value['params'] # Store config
             # Store None in the variable table for the assignment target `loss` itself
             self.variables[target_name] = None 
        elif isinstance(value, dict) and value.get('type') == 'OptimizerDefinition':
            print(f"Configuring optimizer: {value['params']}")
            self.config['optimizer'] = value['params'] # Store config
            # Store None in the variable table for the assignment target `optimizer` itself
            self.variables[target_name] = None
        else:
            # Store the evaluated value directly (e.g., result of evaluate, literals)
            value_to_store = value
            # Special case: if RHS was EvaluateStatement, it already returned the result (e.g., accuracy)
            if isinstance(value, neuro_ast.EvaluateStatement):
                 # Re-visit the EvaluateStatement node to get its *result* for storage
                 # This assumes visit_EvaluateStatement returns the actual value
                 print(f"Re-visiting EvaluateStatement to get result for assignment...")
                 value_to_store = self.visit_EvaluateStatement(value)
                 
            self.variables[target_name] = value_to_store
            print(f"  Stored value of type {type(value_to_store)} for variable '{target_name}'.")
            
        return None # Assignment statement itself doesn't return a value

    def visit_ModelDefinition(self, node: neuro_ast.ModelDefinition):
        """Handles the definition of a neural network model (as RHS of assignment)."""
        # This visitor is now called when evaluating the RHS of an assignment
        # It prepares the information needed to create the NeuralNetwork object
        model_name = node.name # Name is now set during assignment
        print(f"Processing ModelDefinition for: {model_name or '(unassigned yet)'}")
        print(f"  Parameters: {node.params}")
        
        # Process layer nodes to potentially validate or prepare them
        processed_layers = []
        for layer_node in node.layers:
            if not isinstance(layer_node, neuro_ast.Layer):
                 raise NeuroInterpreterError(f"Expected Layer node in ModelDefinition, got {type(layer_node)}")
            layer_info = self.visit(layer_node)
            processed_layers.append(layer_info)
            
        # Return a dictionary describing the model to be created by the Assignment visitor
        return {
            'type': 'ModelDefinition',
            'name': model_name,
            'params': node.params,
            'layers': node.layers # Pass the original Layer AST nodes to the constructor
        }

    def visit_Layer(self, node: neuro_ast.Layer):
        """Handles a layer definition within a model."""
        # This method might not be called directly if ModelDefinition handles layers internally,
        # but it's good practice to have it.
        print(f"  Processing layer: {node.layer_type} with params {node.params}")
        # In a real implementation, might validate params or create a layer object spec
        return {'type': node.layer_type, 'params': node.params}

    # --- Placeholders for other statements ---

    def visit_LossDefinition(self, node: neuro_ast.LossDefinition):
        """Handles Loss(...) call (as RHS of assignment)."""
        print(f"Processing LossDefinition call: {node.params}")
        # Return a dictionary describing the loss config
        return {'type': 'LossDefinition', 'params': node.params}

    def visit_OptimizerDefinition(self, node: neuro_ast.OptimizerDefinition):
        """Handles Optimizer(...) call (as RHS of assignment)."""
        print(f"Processing OptimizerDefinition call: {node.params}")
        # Return a dictionary describing the optimizer config
        return {'type': 'OptimizerDefinition', 'params': node.params}

    def visit_TrainStatement(self, node: neuro_ast.TrainStatement):
        model_name = node.model_name
        data_source_name = node.data_source.name if isinstance(node.data_source, neuro_ast.Identifier) else str(node.data_source)
        
        print(f"Initiating training for model '{model_name}'")
        print(f"  Data source: {data_source_name}")
        print(f"  Training parameters: {node.params}")
        if model_name not in self.variables:
            raise NeuroNameError(f"Variable '{model_name}' is not defined.")
            
        model_object = self.variables.get(model_name)
        if not isinstance(model_object, NeuralNetwork):
             raise NeuroTypeError(f"Variable '{model_name}' is not a trainable NeuralNetwork object (found {type(model_object)})." )
             
        # TODO: Load data (using NeuroMatrix?)
        # TODO: Get loss and optimizer from self.config
        # TODO: Implement actual training loop using PyTorch
        print(f"(Placeholder) Training model '{model_name}' ({type(model_object)})...")
        return None # Or return training history/metrics

    def visit_EvaluateStatement(self, node: neuro_ast.EvaluateStatement):
        model_name = node.model_name
        data_source_name = node.data_source.name if isinstance(node.data_source, neuro_ast.Identifier) else str(node.data_source)
        
        print(f"Initiating evaluation for model '{model_name}'")
        print(f"  Data source: {data_source_name}")
        if model_name not in self.variables:
            raise NeuroNameError(f"Variable '{model_name}' is not defined.")
            
        model_object = self.variables.get(model_name)
        if not isinstance(model_object, NeuralNetwork):
             raise NeuroTypeError(f"Variable '{model_name}' is not an evaluatable NeuralNetwork object (found {type(model_object)})." )
             
        # TODO: Load data
        # TODO: Implement evaluation logic using the PyTorch model
        print(f"(Placeholder) Evaluating model '{model_name}' ({type(model_object)})...")
        # Placeholder return value
        accuracy = 0.95 # Dummy accuracy
        print(f"(Placeholder) Evaluation result (accuracy): {accuracy}")
        return accuracy
        
    def visit_Identifier(self, node: neuro_ast.Identifier):
        """Handles retrieving the value of a variable."""
        var_name = node.name
        if var_name in self.variables:
            print(f"Retrieving variable: {var_name}")
            return self.variables[var_name]
        # Check if it's a data source identifier or similar global?
        # For now, assume only defined variables are identifiers
        else:
            raise NeuroNameError(f"Variable '{var_name}' is not defined.")
            
    def visit_NumberLiteral(self, node: neuro_ast.NumberLiteral):
        """Handles number literals."""
        return node.value
        
    def visit_StringLiteral(self, node: neuro_ast.StringLiteral):
        """Handles string literals."""
        return node.value 