# NEURO Interpreter: Executes the Abstract Syntax Tree (AST) generated by the parser.

# Import AST node types and custom errors
import sys
import os
import src.neuro_ast as neuro_ast # Use alias to avoid standard library conflicts
from src.errors import NeuroInterpreterError, NeuroNameError, NeuroTypeError, NeuroError, NeuroDataError
# Import the actual network model
from src.models import NeuralNetwork
import torch
# from src.parser import NeuroParser, neuro_ast # Assuming neuro_ast contains AST node definitions -> Redundant?
# from src.interpreter import NeuroInterpreter # Keep existing import if needed -> Redundant?
# from src.errors import NeuroError, NeuroNameError, NeuroTypeError # Import relevant errors -> Redundant?
# from src.models import NeuralNetwork # Import NeuralNetwork -> Redundant?
from src.matrix import NeuroMatrix, NeuroDataError # Import NeuroMatrix and its error

class NeuroInterpreter:
    def __init__(self):
        """Initializes the interpreter's state."""
        self.variables = {}  # Symbol table for variables
        self.functions = { # Built-in functions
            'print': self._print_function,
            'load_matrix': self._load_matrix_function, # Add load_matrix
            # Add other built-in functions here
        } 
        self.config = { # Holds configuration like loss, optimizer settings
            'loss': None, 
            'optimizer': None
        }
        # Add any other necessary state, e.g., for model tracking

    def interpret(self, node):
        """Interprets the AST starting from the given node (usually Program)."""
        # The main entry point now expects an AST node object
        if not isinstance(node, neuro_ast.ASTNode):
            raise NeuroInterpreterError(f"Interpreter received non-AST input: {type(node)}")
        
        print("Interpreting AST...")
        result = self.visit(node) # Start visiting from the root node
        print("Interpretation complete.")
        return result # Might return final evaluation result, etc.

    def visit(self, node):
        """Visits a node in the AST and calls the appropriate handler."""
        # Use the class name of the node to find the visitor method
        method_name = f'visit_{node.__class__.__name__}'
        visitor = getattr(self, method_name, self.generic_visit)
        # print(f"Visiting {node.__class__.__name__} using {visitor.__name__}") # Debugging
        # Handle potential None nodes if parser allows them (e.g., empty statements)
        if node is None:
             return None
        return visitor(node)

    def generic_visit(self, node):
        """Handles unknown AST node types."""
        raise NeuroInterpreterError(f"No visitor method found for AST node type '{node.__class__.__name__}'")

    # --- Visitor Methods for AST Nodes ---

    def visit_Program(self, node: neuro_ast.Program):
        """Executes all statements in the program body."""
        last_result = None
        for statement in node.body:
            last_result = self.visit(statement)
        return last_result # Return result of the last statement

    def visit_AssignmentStatement(self, node: neuro_ast.AssignmentStatement):
        """Handles assignment statements like 'var = expression' or 'v1, v2 = expression'"""
        # target_name = node.target.name
        # print(f"Assigning to variable: {target_name}")
        
        # Evaluate the right-hand side expression first
        rhs_value = self.visit(node.value) 
        
        # Check if it's tuple assignment or single assignment
        if isinstance(node.target, list): 
            # Tuple Assignment
            targets = node.target
            target_names = [t.name for t in targets]
            print(f"Assigning to multiple variables: {', '.join(target_names)}")
            
            # Check if RHS value is a sequence of the correct length
            if not isinstance(rhs_value, (list, tuple)):
                 raise NeuroTypeError(f"Cannot unpack non-sequence value of type {type(rhs_value).__name__} into multiple targets ({len(targets)} targets)")
            if len(rhs_value) != len(targets):
                 raise NeuroTypeError(f"Value mismatch: Expected {len(targets)} values to unpack, but got {len(rhs_value)} from expression")
                 
            # Perform assignment
            for i, target_node in enumerate(targets):
                var_name = target_node.name
                assigned_value = rhs_value[i]
                self.variables[var_name] = assigned_value
                print(f"  Assigned value of type {type(assigned_value).__name__} to variable '{var_name}'.")
                
        elif isinstance(node.target, neuro_ast.Identifier):
            # Single Assignment
            target_name = node.target.name
            print(f"Assigning to variable: {target_name}")
            
            # Handle specific definition types that configure things
            if isinstance(rhs_value, dict) and rhs_value.get('type') == 'ModelDefinition':
                model_params = rhs_value['params']
                model_layers = rhs_value['layers']
                # Name should have been set by parser here
                model_object = NeuralNetwork(name=rhs_value['name'], params=model_params, layer_nodes=model_layers)
                self.variables[target_name] = model_object
                print(f"  Stored NeuralNetwork object '{target_name}' in variables.")
            elif isinstance(rhs_value, dict) and rhs_value.get('type') == 'LossDefinition':
                 print(f"Configuring loss: {rhs_value['params']}")
                 self.config['loss'] = rhs_value['params'] 
                 self.variables[target_name] = None # Assign None to the variable 'loss' itself
            elif isinstance(rhs_value, dict) and rhs_value.get('type') == 'OptimizerDefinition':
                print(f"Configuring optimizer: {rhs_value['params']}")
                self.config['optimizer'] = rhs_value['params'] 
                self.variables[target_name] = None # Assign None to the variable 'optimizer' itself
            else:
                # For all other expressions (literals, function calls, etc.), store the value directly.
                self.variables[target_name] = rhs_value
                print(f"  Stored value of type {type(rhs_value).__name__} for variable '{target_name}'.")
        else:
            # Should not happen if parser creates correct AST
            raise NeuroInterpreterError(f"Unexpected target type in AssignmentStatement: {type(node.target)}")
            
        return None # Assignment statement itself doesn't return a value

    def visit_ModelDefinition(self, node: neuro_ast.ModelDefinition):
        """Handles the definition of a neural network model (as RHS of assignment)."""
        # This visitor is now called when evaluating the RHS of an assignment
        # It prepares the information needed to create the NeuralNetwork object
        model_name = node.name # Name is now set during assignment
        print(f"Processing ModelDefinition for: {model_name or '(unassigned yet)'}")
        print(f"  Parameters: {node.params}")
        
        # Process layer nodes to potentially validate or prepare them
        processed_layers = []
        for layer_node in node.layers:
            if not isinstance(layer_node, neuro_ast.Layer):
                 raise NeuroInterpreterError(f"Expected Layer node in ModelDefinition, got {type(layer_node)}")
            layer_info = self.visit(layer_node)
            processed_layers.append(layer_info)
            
        # Return a dictionary describing the model to be created by the Assignment visitor
        return {
            'type': 'ModelDefinition',
            'name': model_name,
            'params': node.params,
            'layers': node.layers # Pass the original Layer AST nodes to the constructor
        }

    def visit_Layer(self, node: neuro_ast.Layer):
        """Handles a layer definition within a model."""
        # This method might not be called directly if ModelDefinition handles layers internally,
        # but it's good practice to have it.
        print(f"  Processing layer: {node.layer_type} with params {node.params}")
        # In a real implementation, might validate params or create a layer object spec
        return {'type': node.layer_type, 'params': node.params}

    # --- Placeholders for other statements ---

    def visit_LossDefinition(self, node: neuro_ast.LossDefinition):
        """Handles Loss(...) call (as RHS of assignment)."""
        print(f"Processing LossDefinition call: {node.params}")
        # Return a dictionary describing the loss config
        return {'type': 'LossDefinition', 'params': node.params}

    def visit_OptimizerDefinition(self, node: neuro_ast.OptimizerDefinition):
        """Handles Optimizer(...) call (as RHS of assignment)."""
        print(f"Processing OptimizerDefinition call: {node.params}")
        # Return a dictionary describing the optimizer config
        return {'type': 'OptimizerDefinition', 'params': node.params}

    def visit_TrainStatement(self, node: neuro_ast.TrainStatement):
        model_name = node.model_name
        if not isinstance(node.data_source, neuro_ast.Identifier):
             raise NeuroTypeError(f"Training data source for model '{model_name}' must be a variable name (Identifier), got {type(node.data_source)}")
        data_source_name = node.data_source.name
        
        print(f"Interpreter: Initiating training for model '{model_name}'")
        
        # --- Get Model ---
        # Check if model variable exists FIRST
        if model_name not in self.variables:
             raise NeuroNameError(f"Variable '{model_name}' is not defined.")
             
        model_object = self.variables.get(model_name)
        # THEN check if it's the right type
        if not isinstance(model_object, NeuralNetwork):
             raise NeuroTypeError(f"Variable '{model_name}' is not a trainable NeuralNetwork object (found {type(model_object)}).")
             
        # --- Get Data ---
        # Check if data variable exists FIRST
        if data_source_name not in self.variables:
            raise NeuroNameError(f"Data variable '{data_source_name}' is not defined.")
            
        data_object = self.variables.get(data_source_name)
        # THEN check if it's the right type
        if not isinstance(data_object, NeuroMatrix):
             raise NeuroTypeError(f"Data variable '{data_source_name}' is not a NeuroMatrix object (found {type(data_object)}).")
             
        # Extract data and convert to tensors
        try:
            X = torch.tensor([item['input'] for item in data_object.data], dtype=torch.float32)
            y = torch.tensor([item['output'] for item in data_object.data], dtype=torch.float32)
            if len(y.shape) == 1:
                y = y.unsqueeze(1)
        except (KeyError, TypeError, ValueError) as e:
             raise NeuroDataError(f"Error processing data from '{data_source_name}': {e}")

        print(f"  Data source: {data_source_name} (Loaded {len(X)} samples)")
        
        # --- Get Optional Validation Data ---
        validation_data_name = node.params.get('validation_data') # Check for validation_data param
        X_val, y_val = None, None
        if validation_data_name:
            if not isinstance(validation_data_name, str):
                raise NeuroTypeError(f"'validation_data' parameter for training '{model_name}' must be a string variable name, got {type(validation_data_name)}")
            if validation_data_name not in self.variables:
                raise NeuroNameError(f"Validation data variable '{validation_data_name}' is not defined.")
                
            val_data_object = self.variables.get(validation_data_name)
            if not isinstance(val_data_object, NeuroMatrix):
                raise NeuroTypeError(f"Validation data variable '{validation_data_name}' is not a NeuroMatrix object (found {type(val_data_object)})." )
                
            try:
                X_val = torch.tensor([item['input'] for item in val_data_object.data], dtype=torch.float32)
                y_val = torch.tensor([item['output'] for item in val_data_object.data], dtype=torch.float32)
                if len(y_val.shape) == 1:
                    y_val = y_val.unsqueeze(1)
                print(f"  Validation data source: {validation_data_name} (Loaded {len(X_val)} samples)")
            except (KeyError, TypeError, ValueError) as e:
                raise NeuroDataError(f"Error processing validation data from '{validation_data_name}': {e}")
        else:
             print("  No validation data provided.")

        # --- Get Loss/Optimizer Config from Interpreter State ---
        loss_config = self.config.get('loss')
        optimizer_config = self.config.get('optimizer')

        if not loss_config or not isinstance(loss_config, dict):
             raise NeuroError(f"Loss function not properly configured before training '{model_name}'. Use 'loss = Loss(type=...)'.")
        if not optimizer_config or not isinstance(optimizer_config, dict):
             raise NeuroError(f"Optimizer not properly configured before training '{model_name}'. Use 'optimizer = Optimizer(type=...)'.")

        # --- Extract parameters needed by train_model --- 
        try:
            loss_fn_name = loss_config.get('type')
            optimizer_name = optimizer_config.get('type')
            learning_rate = float(optimizer_config.get('learning_rate', 0.001))
            
            epochs = int(node.params.get('epochs', 10)) 
            batch_size = int(node.params.get('batch_size', 32)) 
            
            if not loss_fn_name or not optimizer_name:
                 raise NeuroTypeError("Loss/Optimizer configuration missing 'type' parameter.")
                 
        except (ValueError, TypeError, KeyError) as e:
            raise NeuroTypeError(f"Invalid or missing parameter in Loss/Optimizer/Train configuration for '{model_name}': {e}")

        print(f"  Extracted Loss Type: {loss_fn_name}")
        print(f"  Extracted Optimizer Type: {optimizer_name}")
        print(f"  Extracted LR: {learning_rate}")
        print(f"  Extracted Epochs: {epochs}")
        print(f"  Extracted Batch Size: {batch_size}")

        # --- Call the actual training method with correct arguments ---
        history = model_object.train_model(
            X_train=X, 
            y_train=y, 
            loss_fn_name=loss_fn_name,
            optimizer_name=optimizer_name,
            epochs=epochs, 
            learning_rate=learning_rate,
            batch_size=batch_size,
            X_val=X_val, # Pass validation data
            y_val=y_val  # Pass validation data
        )
        
        print(f"Interpreter: Finished training model '{model_name}'.")
        return history

    def visit_EvaluateStatement(self, node: neuro_ast.EvaluateStatement):
        model_name = node.model_name
        if not isinstance(node.data_source, neuro_ast.Identifier):
            raise NeuroTypeError(f"Data source for evaluate must be an identifier, got {type(node.data_source)}")
        data_source_name = node.data_source.name

        print(f"Initiating evaluation for model '{model_name}'")
        print(f"  Data source: {data_source_name}")
        if model_name not in self.variables:
            raise NeuroNameError(f"Variable '{model_name}' is not defined.")
            
        model_object = self.variables.get(model_name)
        if not isinstance(model_object, NeuralNetwork):
            raise NeuroTypeError(f"Variable '{model_name}' is not an evaluatable NeuralNetwork object (found {type(model_object)})." )

        # --- Get Data ---
        if data_source_name not in self.variables:
            raise NeuroNameError(f"Data variable '{data_source_name}' is not defined.")
        data_object = self.variables.get(data_source_name)
        if not isinstance(data_object, NeuroMatrix):
             raise NeuroTypeError(f"Data variable '{data_source_name}' is not a NeuroMatrix object (found {type(data_object)})." )

        try:
            X_eval = torch.tensor([item['input'] for item in data_object.data], dtype=torch.float32)
            y_eval = torch.tensor([item['output'] for item in data_object.data], dtype=torch.float32)
            if len(y_eval.shape) == 1:
                y_eval = y_eval.unsqueeze(1)
        except (KeyError, TypeError, ValueError) as e:
             raise NeuroDataError(f"Error processing evaluation data from '{data_source_name}': {e}")
        print(f"  Loaded evaluation data: {len(X_eval)} samples")

        # --- Get Loss Config (needed for loss calculation) ---
        loss_config = self.config.get('loss')
        if not loss_config or not isinstance(loss_config, dict):
             # Allow evaluation without pre-configured loss for just predictions?
             # For now, require loss config to report loss.
             print(f"Warning: Loss function not configured. Cannot report evaluation loss for model '{model_name}'.")
             loss_fn_name = None
             # raise NeuroError(f"Loss function not properly configured before evaluating '{model_name}'. Use 'loss = Loss(type=...)'.")
        else:
            loss_fn_name = loss_config.get('type')
            if not loss_fn_name:
                raise NeuroTypeError("Loss configuration missing 'type' parameter during evaluation.")

        # --- Perform Evaluation ---
        # Use the evaluate method from the NeuralNetwork class
        results = model_object.evaluate(
            X_eval=X_eval,
            y_eval=y_eval,
            loss_fn_name=loss_fn_name # Pass loss function name
            # Remove batch_size for now as EvaluateStatement has no params
            # batch_size=int(node.params.get('batch_size', 32))
        )

        print(f"Interpreter: Evaluation complete for model '{model_name}'. Results: {results}")
        # Return the results dictionary (e.g., {'loss': ..., 'accuracy': ...})
        return results
        
    def visit_Identifier(self, node: neuro_ast.Identifier):
        """Handles retrieving the value of a variable."""
        var_name = node.name
        if var_name in self.variables:
            print(f"Retrieving variable: {var_name}")
            return self.variables[var_name]
        # Check if it's a data source identifier or similar global?
        # For now, assume only defined variables are identifiers
        else:
            raise NeuroNameError(f"Variable '{var_name}' is not defined.")
            
    def visit_NumberLiteral(self, node: neuro_ast.NumberLiteral):
        """Handles number literals."""
        return node.value
        
    def visit_StringLiteral(self, node: neuro_ast.StringLiteral):
        """Handles string literals."""
        return node.value 

    def visit_FunctionCall(self, node: neuro_ast.FunctionCall):
        """Handles calls to built-in functions like load_matrix() or print()."""
        # Ensure func_name is an Identifier node
        if not isinstance(node.func_name, neuro_ast.Identifier):
             # This should not happen if parser is correct, but handle defensively
             raise NeuroInterpreterError(f"Interpreter Error: Function name is not an Identifier node ({type(node.func_name)})")

        func_name_str = node.func_name.name
        print(f"Visiting FunctionCall: {func_name_str}")

        if func_name_str not in self.functions:
            raise NeuroNameError(f"Function '{func_name_str}' is not defined.")

        func = self.functions[func_name_str]
        
        # Evaluate arguments
        evaluated_args = []
        try:
            evaluated_args = [self.visit(arg) for arg in node.args]
        except NeuroError as e: # Catch errors during argument evaluation
            # Re-raise, possibly adding context about the function call
            raise NeuroInterpreterError(f"Error evaluating arguments for function '{func_name_str}': {e}") from e

        print(f"  Evaluated args: {evaluated_args}")

        # Call the corresponding Python function
        target_function = func
        
        # Call the internal function (_load_matrix_function expects the AST node)
        # TODO: Standardize built-in function signatures - some might want evaluated args, others the raw AST node
        if func_name_str == 'load_matrix':
             if len(node.args) != 1:
                  raise NeuroTypeError(f"load_matrix() takes exactly 1 argument (filepath), got {len(node.args)}")
             # Assuming the argument for load_matrix is a StringLiteral or Identifier
             arg_node = node.args[0]
             filepath = None # Define filepath variable outside try
             try:
                 if isinstance(arg_node, neuro_ast.StringLiteral):
                     filepath = arg_node.value # Get filepath from literal
                 elif isinstance(arg_node, neuro_ast.Identifier):
                      # Evaluate the identifier to get the filepath string
                      filepath_var_name = arg_node.name
                      if filepath_var_name not in self.variables:
                           raise NeuroNameError(f"Variable '{filepath_var_name}' used for load_matrix filepath is not defined.")
                      filepath = self.variables[filepath_var_name]
                      if not isinstance(filepath, str):
                           raise NeuroTypeError(f"Variable '{filepath_var_name}' must be a string for load_matrix, got {type(filepath)}.")
                 else:
                     raise NeuroTypeError(f"load_matrix() argument must be a string literal or a variable containing a string, got {type(arg_node)}")

                 # Call the internal function with the resolved filepath string
                 return target_function(filepath) # Call _load_matrix_function

             # Catch specific NeuroErrors from resolving/type checking or from _load_matrix_function
             except (NeuroNameError, NeuroTypeError, NeuroDataError, NeuroInterpreterError) as e:
                 raise e # Re-raise these directly
             # Catch unexpected Python errors during resolution or the call itself
             except Exception as e:
                  # Wrap unexpected errors in NeuroInterpreterError
                  raise NeuroInterpreterError(f"Unexpected error during load_matrix execution for path '{filepath}': {e}") from e

        elif func_name_str == 'print':
            # Call print with evaluated arguments
            try:
                 return target_function(*evaluated_args) # Call with evaluated values
            except Exception as e:
                 # If the print function itself raises an error (less likely for basic print)
                 raise NeuroInterpreterError(f"Error during execution of print(): {e}")
        else:
             # Handle other built-in functions if they are added
             # For now, assume others also take evaluated args
             try:
                 return target_function(*evaluated_args)
             except Exception as e:
                  # General error handling for other functions
                  raise NeuroInterpreterError(f"Error during execution of function '{func_name_str}': {e}")

    def visit_SaveStatement(self, node: neuro_ast.SaveStatement):
        """Handles 'model.save("filepath")' statement."""
        model_name = node.model_name
        filepath_node = node.filepath

        # Ensure filepath is a string literal
        if not isinstance(filepath_node, neuro_ast.StringLiteral):
            # This check might be redundant if parser guarantees it
            raise NeuroTypeError(f"save() requires a string literal filepath, got {type(filepath_node)}")
        filepath = filepath_node.value

        print(f"Interpreter: Initiating save for model '{model_name}' to '{filepath}'")

        # --- Get Model ---
        if model_name not in self.variables:
            raise NeuroNameError(f"Variable '{model_name}' is not defined.")
        model_object = self.variables.get(model_name)
        if not isinstance(model_object, NeuralNetwork):
            raise NeuroTypeError(f"Variable '{model_name}' is not a saveable NeuralNetwork object (found {type(model_object)})." )

        # --- Call the actual save method ---
        try:
            model_object.save(filepath)
            print(f"Interpreter: Successfully saved model '{model_name}' to '{filepath}'.")
        except Exception as e:
            # Catch potential errors during save (e.g., file system issues)
            raise NeuroInterpreterError(f"Failed to save model '{model_name}' to '{filepath}': {e}")

        return None # Save statement doesn't return a value

    def visit_MethodCall(self, node: neuro_ast.MethodCall):
        """Handles general method calls like data.split() used as expressions."""
        object_name = node.object_name
        method_name = node.method_name
        args_dict = node.args # This is the dictionary of params from the parser

        print(f"Visiting MethodCall: {object_name}.{method_name}(...)")

        # --- Get Object ---
        if object_name not in self.variables:
            raise NeuroNameError(f"Variable '{object_name}' is not defined.")
        obj = self.variables.get(object_name)

        # --- Get Method --- 
        if not hasattr(obj, method_name):
            raise NeuroInterpreterError(f"Object '{object_name}' of type {type(obj).__name__} has no method '{method_name}'")
        method = getattr(obj, method_name)
        if not callable(method):
            raise NeuroInterpreterError(f"Attribute '{method_name}' of object '{object_name}' is not callable")

        # --- Prepare Arguments ---
        # The parser stores key-value pairs directly in args for MethodCall (like split)
        # We need to evaluate the *values* in the args dictionary if they are AST nodes
        evaluated_args = {}
        try:
            for key, value_node in args_dict.items():
                # Value could be Literal, Identifier, etc.
                 evaluated_args[key] = self.visit(value_node)
        except NeuroError as e:
             raise NeuroInterpreterError(f"Error evaluating arguments for method '{object_name}.{method_name}': {e}") from e

        print(f"  Calling {method_name} on {type(obj).__name__} with evaluated args: {evaluated_args}")

        # --- Call Method --- 
        try:
            result = method(**evaluated_args) # Use keyword arguments
            print(f"  Method call {object_name}.{method_name} returned: {type(result)}")
            return result
        except NeuroError as e: # Catch known Neuro errors from the method
            raise e
        except Exception as e:
            # Catch other errors during the actual method execution
            raise NeuroInterpreterError(f"Error executing method '{object_name}.{method_name}': {e}") # Changed NeuroInterpreterError

    # --- Built-in Function Implementations ---
    def _print_function(self, *args):
        """Implementation of the built-in print function."""
        print("Built-in print:", *args) # Add prefix for clarity
        return None # Print usually doesn't return a value
        
    def _load_matrix_function(self, filepath):
        """Implementation of the built-in load_matrix function."""
        # Filepath is already validated as string by visit_FunctionCall
        print(f"Interpreter: Loading matrix from '{filepath}'...")
        try:
            matrix = NeuroMatrix()
            matrix.load(filepath) # Use the existing load method
            print(f"Interpreter: Successfully loaded matrix '{filepath}'")
            return matrix # Return the loaded NeuroMatrix object
        except FileNotFoundError:
            # Convert FileNotFoundError to a NeuroError the user might see
            raise NeuroInterpreterError(f"Data file not found: '{filepath}'") # Use InterpreterError
        except NeuroDataError as e:
             # Propagate NeuroDataError
             raise e # Let this specific error type through
        except Exception as e:
             # Catch other potential errors during loading
             raise NeuroInterpreterError(f"Failed to load matrix '{filepath}': {e}") # Use InterpreterError 