name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build documentation
      run: cargo doc --workspace --no-deps

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        destination_dir: api-docs

  mdbook:
    name: Build User Guide
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Build book (if exists)
      run: |
        if [ -f book.toml ]; then
          mdbook build
        else
          echo "No mdbook configuration found - skipping"
        fi

    - name: Deploy user guide
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && hashFiles('book.toml') != ''
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
        destination_dir: user-guide